[WIP] set password by env val
chaspy/ask-python pull request #16
Opened 2019-03-13 11:33 UTC by ariririri

2019-03-13 14:32 UTC, ariririri commented
db password can be set by environment variables.
Please review and merge!

2019-03-14 14:19 UTC, chaspy requested changes

2019-03-14 14:19 UTC, chaspy commented on ask/settings.py
> +        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
suggestion```
        'PASSWORD': os.environ['POSTGRES_PASSWORD'], # FIX ME!
```

2019-03-15 00:24 UTC, chaspy approved these changes

2019-03-15 00:24 UTC, chaspy commented
Thanks!

2019-03-15 00:24 UTC, merged